name: Create or Update Release

on:
  push:
    branches:
      - main 

permissions:
  contents: write
  actions: read

jobs:
  update-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Find version from .deb file
        id: get_version
        run: |
          FILE=$(ls *.deb | head -n1)  # Берём первый .deb файл
          echo "DEB FILE: $FILE"
          VERSION=$(echo "$FILE" | sed -n 's/.*_\([0-9.]\+-[0-9]\+\)\.deb/\1/p')
          echo "VERSION: $VERSION"
          echo "TAG=v$VERSION" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create or Update GitHub Release
        run: |
          NAME="Release $VERSION"
          BODY="Автоматический релиз $VERSION"

          if gh release view "$TAG" &>/dev/null; then
            echo "🔄 Release $TAG уже существует, обновляем описание..."
            gh release edit "$TAG" --title "$NAME" --notes "$BODY"
          else
            echo "🚀 Создаём новый релиз $TAG..."
            gh release create "$TAG" --title "$NAME" --notes "$BODY"
          fi

      - name: Upload .deb packages
        run: |
          for file in *.deb; do
            echo "⬆️ Загружаем $file..."
            gh release upload "$TAG" "$file" --clobber
          done

